<?php
// file ixxMS.php
///////////////////////////////////////////////////////////
//
// pja 12-14-2014 review for echo blanking
///////////////////////////////////////////////////////////
// declare your db connection
// for development
include 'PDODAO.PHP';
// for Website
// include 'mysqlDAO.php';
// also include supporting files
include 'refDAO.php'; 
include 'tcvrDAO.php';
include 'SQSQ.php';
?>
